"""empty message

Revision ID: 19b7f8216758
Revises: 
Create Date: 2022-11-29 11:36:40.242501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19b7f8216758"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Show",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("seeking_venue", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("seeking_description", sa.String(length=500), nullable=True)
        )
        # change data type of column 'genres' from string to array
        batch_op.drop_column("genres")
        batch_op.add_column(sa.Column("genres", sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genres", sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("seeking_talent", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("seeking_description", sa.String(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_talent")
        batch_op.drop_column("website")
        batch_op.drop_column("genres")

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_venue")
        batch_op.drop_column("website")
        # rollback column 'genres' to string type
        batch_op.drop_column("genres")
        batch_op.add_column(
            sa.Column(
                "genres", sa.VARCHAR(length=120), autoincrement=False, nullable=True
            )
        )

    op.drop_table("Show")
    # ### end Alembic commands ###
